### ISSUE TITLE
Too few tested models

### ISSUE THREAD

**Issue by KastB** [KastB/asus_wmi#1]
It would be great if you leave a comment if this module works with your laptop model, the name of your model, and how many fans it has

**Comment by Tharre** [comment]
Amazing work!

Add my UX32VD with 2 fans to your list of working devices.

**Comment by KastB** [comment]
Thanks!

Great to hear that it works for a dual fan device. I've added your device to the list of tested devices.

**Comment by Tharre** [comment]
Dammit, except that the actual second fan does not work. Seems like there was something else loaded when I tried it before.

asus_wmi reports only 1 fan.

EDIT: setting asus->num_fans to 2 also doesn't work, GPU fan is shown but setting fan speed fails.

EDIT2: I've uploaded my dsdt.dsl [here](https://gist.github.com/Tharre/af53a55650c03fb91e6e)

Also, you said in a different issue that GFNN should be used to determine the amount of fans, yet currently you use AGFN, why?

**Comment by KastB** [comment]
GFNN does't seem to report the number of controllable fans (I just hoped it means Get FaN Number)

You can find my dsdt here: https://gist.github.com/KastB/c683264acff36a70492c but it's pretty much the same for the fan control functions... Seems like we need to find another way to determine the number of fans.

I'm using GFNN. Nevertheless it's an wmi module, now, thus I have to call all ACPI functions through the wmi interface and GFNN can only be accessed by AGFN.
In more detail the wmi method with the id "0x4E464741" is executed, which calls AGFN.
AGFN calls MF1X (as the parameter MFUN is set to 0x13) which calls MF13 (also because MFUN is 0x13).
As SFUN is set to 0x05 GFNN is executed there, which seems quite useless, now.

I'll try to provide an update, that doesn't make use of GFNN, now.

EDIT: I've commited an update. It would be great if you could report if it solved that problem

**Comment by Tharre** [comment]
It does not, I still get Number of fans: 1.

Edit: the second asus_hwmon_agfn_fan_speed() call returns -1

**Comment by KastB** [comment]
That's bad luck - I'm afraid it's just impossible to control both fans with the wmi interface:
There is one line in the SFNS method: "If (LGreater (FNNB, One))" that prevents controlling the second fan (zero is for setting auto mode, one for the first fan, two would be for the second fan).
There doesn't seem a solution that could get to the kernel.
What happens if you control the first fan? Is the second one just in auto-mode then?

**Comment by Tharre** [comment]
As far as I can tell yes, it's just running in auto-mode. It would be very strange if only the first fan could be controlled with the wmi interface.

**Comment by daringer** [comment]
I can confirm it runs without obvious problems on the UX32VD, without controlling the second fan as expected. You making my asus-fan obsolete ;D damn it! ... I guess you should expect contributions from my side soon... obviously this is the "righter" way to do this...

**Comment by daringer** [comment]
The (asus-fan.c)[https://github.com/daringer/asus-fan/blob/master/asus_fan.c] startup does the "fan-counting" by reading from both, BUT interestingly 

```
ret = acpi_evaluate_integer(NULL, "\\_SB.PCI0.LPCB.EC0.TACH", &params, &value);
```

As to be seen TACH is used for this operation using the acpi_eval-method-family, soooo why not using exactly the same mechanism for asus_wmi, or would this break something? Nonetheless, this is a hack, thus at least a solution for now! 

Further we can always fall back to the good-old strcmp() and match model strings?

**Comment by KastB** [comment]
It's no use - we can't control both fans.

Strcmp is really a bad idea - we should be as general as possible.
