### ISSUE TITLE
Make issue

### ISSUE THREAD

**Issue by o-Chamie-o** [KastB/asus_wmi#4]
Hi,

Thanks for your work. :)

I try to install it on a Debian 8. But I got this message :
root@Me:/home/Me/Téléchargements/asus_wmi-master# make
make -C /lib/modules/3.16.0-4-amd64/build M=$PWD modules
make[1]: **\* /lib/modules/3.16.0-4-amd64/build: Aucun fichier ou dossier de ce type. Arrêt.
Makefile:5: recipe for target 'all' failed
make: **\* [all] Error 2

I think to remember that my Laptop (X5DJI serie) have no PWD fan control.

Can you enlight me, it is a Debian issue, or a hardware issue ?

Thanks in advance,
Best,

**Comment by o-Chamie-o** [comment]
The content of the directory :
root@Me:/# ls -l /lib/modules/3.16.0-4-amd64/
total 3684
drwxr-xr-x 10 root root   4096 janv. 24 13:04 kernel
-rw-r--r--  1 root root 898823 janv. 24 13:07 modules.alias
-rw-r--r--  1 root root 870365 janv. 24 13:07 modules.alias.bin
-rw-r--r--  1 root root   3050 janv. 17 22:27 modules.builtin
-rw-r--r--  1 root root   4256 janv. 24 13:07 modules.builtin.bin
-rw-r--r--  1 root root 372375 janv. 24 13:07 modules.dep
-rw-r--r--  1 root root 508791 janv. 24 13:07 modules.dep.bin
-rw-r--r--  1 root root    402 janv. 24 13:07 modules.devname
-rw-r--r--  1 root root 118257 janv. 17 22:27 modules.order
-rw-r--r--  1 root root    215 janv. 24 13:07 modules.softdep
-rw-r--r--  1 root root 429130 janv. 24 13:07 modules.symbols
-rw-r--r--  1 root root 536873 janv. 24 13:07 modules.symbols.bin

**Comment by KastB** [comment]
Hi,
according to google translate there are some files missing... probably the kernel headers. Have you checked if you have installed them? Something like
`sudo apt-get install linux-headers-$(uname -r)`
could solve this issue.
Cheers
